#ifndef ORDERUPDATEEVENT_H
#define ORDERUPDATEEVENT_H

#include <string>
#include "Order.h"

namespace Huobi {

    /**
     * The order update received by subscription of order update.
     */
    struct OrderUpdateEvent {
        /**
         * The symbol you subscribed.
         */
        std::string symbol;

        /**
         * The UNIX formatted timestamp generated by server in UTC.
         */
        long timestamp;

        /**
         * The order detail.
         */
        Order data;
    };


    struct OrderUpdateEventNew {
        /**
         * The symbol you subscribed.
         */
        std::string symbol;

        /**
         * The UNIX formatted timestamp generated by server in UTC.
         */
        long timestamp;
        std::string role;


        long matchId;
        long id;
        int localId;


        double filled;
        double unfilled;
        double price;
        double filledTurnover;
        OrderState state;
        OrderType type;
    };
}

#endif /* ORDERUPDATEEVENT_H */

