#ifndef PRICEDEPTHEVENT_H
#define PRICEDEPTHEVENT_H

#include <string>
#include "Huobi/PriceDepth.h"

namespace Huobi {

    /*
     * The price depth received by subscription of price depth.
     */
    struct PriceDepthEvent {
        /**
         * The symbol you subscribed.
         */
        std::string symbol;
        
        /**
         * The UNIX formatted timestamp generated by server in UTC.
         */
        long timestamp;
        
        /**
         * The price depth.
         */
        PriceDepth data;
    };
}


#endif /* PRICEDEPTHEVENT_H */

