/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/* 
 * File:   SystemStatus.h
 * Author: yuanxueqi
 *
 * Created on 2020年4月8日, 上午9:44
 */

//#ifndef SYSTEMSTATUS_H
//#define SYSTEMSTATUS_H
//namespace Huobi {
//
//    /**
//     * The trade information with price and amount etc.
//     */
//    struct SystemStatus {
//        /**
//         * The unique trade id of this trade.
//         */
//        std::string tradeId;
//
//        /**
//         * The UNIX formatted timestamp generated by server in UTC.
//         */
//        long timestamp;
//
//        /**
//         * The trading price in quote currency.
//         */
//        Decimal price;
//
//        /**
//         * The trading volume in base currency.
//         */
//        Decimal amount;
//
//        /**
//         * The direction of the taker trade: 'buy' or 'sell'.
//         */
//        TradeDirection direction;
//
//        /**
//         * The unique trade id of this trade. (new)
//         */
//        std::string uniqueTradeId;
//
//    };
//}
//
//
//#endif /* SYSTEMSTATUS_H */

