#ifndef TRADEEVENT_H
#define TRADEEVENT_H

#include <string>
#include <vector>
#include "Huobi/Trade.h"

namespace Huobi {

    /**
     * The trade received by subscription of trade.
     */
    struct TradeEvent {
        /**
         * The symbol you subscribed.
         */
        std::string symbol;

        /**
         * The UNIX formatted timestamp generated by server in UTC.
         */
        long timestamp;

        /**
         * The trade list. The content is Trade class.
         */
        std::vector<Trade> tradeList;

        TradeEvent(com::huobi::gateway::Trade trade) {
            tradeList.push_back(trade);
            timestamp = TimeService::convertCSTInMillisecondToUTC(trade.ts());
            symbol = trade.symbol();

        }

        TradeEvent(com::huobi::gateway::ReqTrade req) {
            int i = req.trades_size();
            for (int j = 0; j < i; j++) {
                tradeList.push_back(req.trades(j));
            }
        }
    };
}

#endif /* TRADEEVENT_H */

